#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# aliases
alias git="hub"
alias s3cmd-dev="s3cmd -c ~/.s3cfg-dev"  # these go away with sourcing
alias s3cmd-prd="s3cmd -c ~/.s3cfg-prd"

# completion definitions
source /usr/local/share/zsh/site-functions/_aws
